Feature: Request options for fetch()
adobe/node-httptransfer pull request #106
Opened 2022-03-24 00:09 UTC by celeryclub

## Description

* Replace [node-fetch-npm](https://github.com/npm/node-fetch-npm) with [node-fetch](https://github.com/node-fetch/node-fetch)
* Fix a Babel polyfilling bug
* Add support for a `requestOptions` parameter in `AEMUpload` and `AEMDownload` that will be passed all the way down to `fetch`

My use case for wanting to pass options to `fetch` is that I want to override the http(s) `agent` used to make the request in order to support request proxying.

Fixes # (issue)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-24 00:17 UTC, tmathern commented
@celeryclub Type of change can only be one type, here it's new feature (important because it will define the version number later).

2022-03-24 00:20 UTC, tmathern requested changes
There is one option we use in Asset Compute, `timeout` (from the npm node-fetch-npm doc: req/res timeout in ms, it resets on redirect. 0 to disable (OS limit applies)), that is not supported by `node-fetch` but is supported by `node-fetch-retry`. We need the support of this option for Asset Compute.

Just by looking very quickly, I didn't find an equivalent for node-fetch. So I wouldn't switch to node-fetch just yet... This is why I requested changes. Passing down transfer/retry params lgtm though.

2022-03-24 00:21 UTC, tmathern commented on lib/aem/aemupload.js
> +            requestOptions,
```suggestion
            requestOptions
```

2022-03-24 00:24 UTC, tmathern commented
Additional note: we have upcoming work to update node-fetch-npm/... and find a viable alternative. If you find alternatives, feel free to suggest some, @celeryclub! Thanks!

2022-03-24 00:32 UTC, celeryclub commented
> There is one option we use in Asset Compute, `timeout` (from the npm node-fetch-npm doc: req/res timeout in ms, it resets on redirect. 0 to disable (OS limit applies)), that is not supported by `node-fetch` but is supported by `node-fetch-retry`. We need the support of this option for Asset Compute.
> 
> Just by looking very quickly, I didn't find an equivalent for node-fetch. So I wouldn't switch to node-fetch just yet... This is why I requested changes. Passing down transfer/retry params lgtm though.

Good to know. I believe the same thing can be accomplished using an `AbortController` in `node-fetch`. But it's not as simple to implement. I'll remove this commit from the PR. It's actually not needed for the work I'm doing right now - I thought it was when I started.

2022-03-24 00:36 UTC, tmathern commented
> > There is one option we use in Asset Compute, `timeout` (from the npm node-fetch-npm doc: req/res timeout in ms, it resets on redirect. 0 to disable (OS limit applies)), that is not supported by `node-fetch` but is supported by `node-fetch-retry`. We need the support of this option for Asset Compute.
> > Just by looking very quickly, I didn't find an equivalent for node-fetch. So I wouldn't switch to node-fetch just yet... This is why I requested changes. Passing down transfer/retry params lgtm though.
> 
> Good to know. I believe the same thing can be accomplished using an `AbortController` in `node-fetch`. But it's not as simple to implement. I'll remove this commit from the PR. It's actually not needed for the work I'm doing right now - I thought it was when I started.

Exactly, it's not a "one-liner", and will need more testing to ensure it works as the timeout option.

2022-03-24 14:25 UTC, jdelbick commented
@celeryclub qs, why did you make this PR as a fork instead of a regular PR? (forks don't run CI tests)

2022-03-24 14:56 UTC, jdelbick reviewed
a few things:
- please make this PR not a draft when you are ready for reviewers to review
- you may need to connect your github with Adobe so it automatically signs the adobe CLA (check #guild-opensource slack for more info)
- since this is a new addition to the API, please also update the README with an example of usage

2022-03-28 22:55 UTC, celeryclub commented on lib/aem/aemdownload.js
> +     * @property {*} requestOptions Options that will be passed to fetch
I'll fix. Thanks!

2022-03-28 23:48 UTC, closed without merging