export concurrent functions as old functions to test e2e
adobe/node-httptransfer pull request #99
Opened 2021-12-22 22:16 UTC by jdelbick

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-12-22 22:58 UTC, tmathern approved these changes

2022-01-07 23:08 UTC, tmathern commented on lib/index.js
> +// const { uploadAEMMultipartFile } = require('./aemmultipart');
That one is needed for the desktop app, we can't remove it

2022-01-07 23:09 UTC, tmathern requested changes
We can't change the exports, because some are used by the desktop app. We need to leave AEM-related stuff alone.

2022-01-07 23:11 UTC, jdelbick commented
@tmathern this PR is not meant to be merged. it is just meant for testing and getting and IT endpoint for free where blocktransfer changes will be used inside the workers

2022-01-11 20:38 UTC, closed without merging